<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b04a072c-8e32-4252-8809-1d3b70c2d995</elementGuidId>
    <imagePath></imagePath>
    <name>button_continue_to_shipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeLarge\\ MuiButton-containedSizeLarge\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeLarge\\ MuiButton-containedSizeLarge\\ css-110xwq5"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO SHIPPING')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO SHIPPING</value>
        <webElementGuid>9c6649bc-92af-403b-bb4d-6299a9e1dfb1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>9c6649bc-92af-403b-bb4d-6299a9e1dfb1</webElementGuid>
    </webElementProperties>
</WebElementEntity>