<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>44bfb9a3-5171-4c1f-b7e7-e9224510247c</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>