<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bea82b45-45aa-4995-b8a0-69bef5f68f63</elementGuidId>
    <imagePath></imagePath>
    <name>input_price_min</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="category-filters\ px-1"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'desk_filter_price_min') and equals(@name,'price_min') and equals(@class,'form-control form-control-sm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-control form-control-sm</value>
        <webElementGuid>16a0c6ff-b5cb-4051-be82-0fda68d101d1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>desk_filter_price_min</value>
        <webElementGuid>a9587fc9-0735-416f-8f67-23495d215968</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>price_min</value>
        <webElementGuid>5c364afa-6ddb-4db5-99a2-d1a2fef3bc6f</webElementGuid>
    </webElementProperties>
</WebElementEntity>