<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>52937467-8bc2-4db6-8bc7-bffb3072a150</elementGuidId>
    <imagePath></imagePath>
    <name>button_increased</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Increased']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary text-center') and equals(@title,'Increased')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary text-center</value>
        <webElementGuid>c180b3b2-828d-4803-9a68-b3973974e2ca</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Increased</value>
        <webElementGuid>f0ea1944-df7a-46f4-9753-fcdef041ccc3</webElementGuid>
    </webElementProperties>
</WebElementEntity>