<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>14cdc2f0-b4c9-47d8-806a-99a417b104aa</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_place_an_order</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-action\\ btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Place an order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place an order</value>
        <webElementGuid>3bd8a220-f3c6-4696-94de-d6eb347542af</webElementGuid>
    </webElementProperties>
</WebElementEntity>