<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0db50796-3eb0-4a0f-b6f5-2bf50ae20c58</elementGuidId>
    <imagePath></imagePath>
    <name>button_proceedCheckout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn btn-action btn-lg btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Proceed to checkout')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button &gt;&gt; nth=3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Proceed to checkout</value>
        <webElementGuid>888e57ad-1c0c-451e-b0fd-81dd703937e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>