<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fdd5ee0a-b85f-4561-88e3-40460c2b9933</elementGuidId>
    <imagePath></imagePath>
    <name>button_increased</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn btn-outline-secondary text-center"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Increased') and equals(@type,'button') and equals(@text,'+')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Increased</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
</WebElementEntity>