<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c3ee2906-5dfa-405a-b768-4bdda0b77f51</elementGuidId>
    <imagePath></imagePath>
    <name>button_proceed_to_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-action\\ btn-lg\\ btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Proceed to checkout')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Proceed to checkout</value>
        <webElementGuid>25ae0338-636d-4d3e-982a-624599947eb5</webElementGuid>
    </webElementProperties>
</WebElementEntity>