<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a117a439-8270-47f2-8c32-a82c55ed9c4f</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(2) [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn') and equals(@title,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-to-cart products__to-cart-btn</value>
        <webElementGuid>24346c2e-6cb9-4123-8aa5-d90a9144eec1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>004d8ad3-cf37-494a-ba83-a7591d0141db</webElementGuid>
    </webElementProperties>
</WebElementEntity>