<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5ce481d9-b4ba-42a2-a3d9-8cbf766c7b90</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_by_price</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sort-buttons__element\\ active"] &gt; [class="sort-buttons__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'By price')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="By price"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>By price</value>
        <webElementGuid>93bb97d2-a60d-4527-a721-9e96f32c824f</webElementGuid>
    </webElementProperties>
</WebElementEntity>