<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>13765e34-8657-41ff-a428-c0605745af0a</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[itemscope][data-id='\31 94'] .btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn') and equals(@title,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-to-cart products__to-cart-btn</value>
        <webElementGuid>f8ea84ce-151b-405d-8036-a1e47eaff222</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>9f51b8d7-dd09-496e-9cb7-12e7d16fce29</webElementGuid>
    </webElementProperties>
</WebElementEntity>