<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f56c5a8-59cf-4f4f-882d-df3daa165b18</elementGuidId>
    <imagePath></imagePath>
    <name>div_dialog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="dialog"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=dialog</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>