<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eb89c96a-9498-4014-8337-173a2ed41db6</elementGuidId>
    <imagePath></imagePath>
    <name>div_iLikeTheQualityAndThe</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[3]/div[2]/div[1]/div[2]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="reviews__item"]:nth-child(2) &gt; [class="reviews__comment"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="I like the quality and the"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>