<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7e6adae6-6d14-4e35-8ec7-63a02a005e45</elementGuidId>
    <imagePath></imagePath>
    <name>div_productsSliderWrapper</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="swiper-slide products-slider__slide"]:nth-child(3) [class="products-slider__product-wrapper"] &gt; div:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(3) &gt; .products-slider__product &gt; .products-slider__product-wrapper &gt; div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>