<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ddf9433d-fd4c-49b5-b37e-8b504719a6b7</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="\31 52175-case-657"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>