<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>407c064a-f12b-4605-a090-479820ce319f</elementGuidId>
    <imagePath></imagePath>
    <name>label_naturalTitanium</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="31 52176-case-660"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Natural Titanium"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>