<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>73b17858-e242-46c5-8a2d-824d9bb1e5ac</elementGuidId>
    <imagePath></imagePath>
    <name>radio_cashOnDelivery</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="PrivateSwitchBase-input css-1m9pwf3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'payment_method_id') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Cash on delivery *"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>payment_method_id</value>
        <webElementGuid>3f45787b-5eeb-432a-928b-82c3afffbd41</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>3f45787b-5eeb-432a-928b-82c3afffbd41</webElementGuid>
    </webElementProperties>
</WebElementEntity>