<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff878470-9a49-4e29-8615-b294db4322be</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_phone</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__element\ is-link\ is-root\ active\ children-visible"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'horizontal-menu__element is-link is-root active children-visible')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>horizontal-menu__element is-link is-root active children-visible</value>
        <webElementGuid>542a8c24-8d23-4f2c-ac79-d186252381d8</webElementGuid>
    </webElementProperties>
</WebElementEntity>