<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe803d61-d8a9-481d-9665-3214fa6cd3d4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_samsung</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__child-element"]:nth-child(2) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Samsung')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung</value>
        <webElementGuid>9afa63c9-858c-4a4e-85f8-38e843cea3c8</webElementGuid>
    </webElementProperties>
</WebElementEntity>