<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>35bb9eee-ee72-4fef-98a9-d2fb84b30939</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="\\31 52179-case-670"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="256 GB"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>