<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>534f357c-e14b-4858-88eb-0c98f9b0c6a1</elementGuidId>
    <imagePath></imagePath>
    <name>button_iPhone15Case2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[5]/div[1]/div[2]/div[2]/button[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item in-stock products__item_3-in-row"]:nth-child(5) [class="svg-inline--fa fa-cart-plus fa-w-18 "]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="iPhone 15 FineWoven Case with"i &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>