<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>457ce8a4-73bc-4a98-a012-9efdf93277c6</elementGuidId>
    <imagePath></imagePath>
    <name>button_show4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="submit"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Show (4)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=group &gt;&gt; internal:role=button &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Show (4)</value>
        <webElementGuid>3f45787b-5eeb-432a-928b-82c3afffbd41</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>3f45787b-5eeb-432a-928b-82c3afffbd41</webElementGuid>
    </webElementProperties>
</WebElementEntity>