<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>40b3718d-11d1-4e4f-9ccd-13047cac3a64</elementGuidId>
    <imagePath></imagePath>
    <name>button_buyDialog2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn btn-action btn-anim btn-lg"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Buy') and equals(@type,'button') and equals(@text,'Buy')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=dialog &gt;&gt; internal:role=button &gt;&gt; nth=3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Buy</value>
        <webElementGuid>37816160-0d03-487a-838b-221fe2fe863e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Buy</value>
        <webElementGuid>37816160-0d03-487a-838b-221fe2fe863e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>37816160-0d03-487a-838b-221fe2fe863e</webElementGuid>
    </webElementProperties>
</WebElementEntity>