<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9650bcae-69f1-48eb-9a3a-d5798e2585d3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.sort-buttons__element.active .sort-buttons__link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sort-buttons__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sort-buttons__link</value>
        <webElementGuid>2388f184-15a4-4f6a-86f6-f1d1187bab35</webElementGuid>
    </webElementProperties>
</WebElementEntity>