<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>522a751d-6256-4e54-982b-f45531fcc276</elementGuidId>
    <imagePath></imagePath>
    <name>link_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Go to cart') and equals(@href,'/cart') and equals(@text,'1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section &gt;&gt; internal:role=link &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/cart</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>1</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Go to cart</value>
        <webElementGuid>2dfd26cc-abfa-48f7-9769-8b461a2171f7</webElementGuid>
    </webElementProperties>
</WebElementEntity>