<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c3006fa4-01be-4364-ac00-a2b07b1070da</elementGuidId>
    <imagePath></imagePath>
    <name>link_kCellphoneShop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mars-logo-row__logo"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'K Cellphone Shop')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="K Cellphone Shop"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>K Cellphone Shop</value>
        <webElementGuid>fc57ced1-9ba9-4a82-9855-391e8a8e7d69</webElementGuid>
    </webElementProperties>
</WebElementEntity>