<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e3f7f81b-0ab6-4382-bcab-0254d2461026</elementGuidId>
    <imagePath></imagePath>
    <name>link_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cart-header cart-header_active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Go to cart') and equals(@href,'/cart') and equals(@text,'2')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section &gt;&gt; internal:role=link &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/cart</value>
        <webElementGuid>888e57ad-1c0c-451e-b0fd-81dd703937e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>2</value>
        <webElementGuid>888e57ad-1c0c-451e-b0fd-81dd703937e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Go to cart</value>
        <webElementGuid>888e57ad-1c0c-451e-b0fd-81dd703937e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>